# Site settings
title: metroize
email: kris.krause@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Technology software development blog - android, unit testing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dragthor.github.io" # the base hostname & protocol for your site
twitter_username: dragthor
github_username:  dragthor

# Build settings
markdown: kramdown
